### ISSUE TITLE
feat: custom DBC attributes 

### ISSUE THREAD

**Issue by t-bre** [sufst/can-defs#8]
### Description
It would be extremely useful to define some custom attributes in the DBC file to help with telemetry system code generation. Currently, Kvaser Database Editor 3 does not support this. Useful attributes to add would be:

- Wireless telemetry priority (e.g. 1 to 5).
- Unique telemetry PDU number (any integer).
- Enabled / disabled (true / false).

### Additional Notes
There are tools for working with DBC files other than Kvaser database editor which might support this functionality.

**Comment by t-bre** [comment]
@AndreasDemenagas this would be a good members task if you have anyone that is looking for something to do any time soon.

**Comment by AndreasDemenagas** [comment]
> @AndreasDemenagas this would be a good members task if you have anyone that is looking for something to do any time soon.

I agree. We can talk about potential attributes tomorrow :)

**Comment by AndreasDemenagas** [comment]
@t-bre Came across the following command-line tool / python module. Not really sure if it helps or not but it does seem to provide a command-line argument for adding custom attributes to a DBC file (`--additionalSignalAttributes`). 

https://github.com/ebroecker/canmatrix

**Comment by t-bre** [comment]
Managed to add a custom attribute using the version of Vector CANdb++ that comes with their [CANAnalyzer Demo software](https://www.vector.com/int/en/know-how/can/?gclid=CjwKCAiAr4GgBhBFEiwAgwORrfiizIGHlOuImdNMMETd6BvsKzls4A67V7nT1sgNeYFulSruOdfpCxoCreoQAvD_BwE). Need to experiment further with how this integrates with our system, but in general it looks promising.

**Comment by t-bre** [comment]
@AndreasDemenagas confirmed now that this works with CANtools and we can get the custom attributes out. For now I will add two attributes: one to enable/disable telemetry and another to set the PDU ID so we can configure them. This will be reflected in the generated schema - if a message is disabled, it will not be added to the schema.

@rureverek for OCT, this will need some changes. In the next release of the defs there will be new entries in the handler table:
- ~~One `bool` enabling/disabling that CAN message from being transmitted via telemetry. This should be checked when setting up RTCAN subscriptions and if it is `false`, that message should not be subscribed to. This way CAN messages which we don't care about will be ignored.~~ Instead of this, will just not add it to the table if disabled, this is less work.
- One `uint32_t` (I think?) PDU identifier, which should replace the current method of using the table index as the ID.
